# Generated by Django 5.2.6 on 2025-10-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BostonQualifier',
            fields=[
                ('resultId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('athleteId', models.CharField(blank=True, max_length=50, null=True)),
                ('Year', models.IntegerField()),
                ('Race', models.CharField(blank=True, max_length=200, null=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('Zip', models.CharField(blank=True, max_length=20, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Age_Group', models.CharField(blank=True, max_length=20, null=True)),
                ('Finish', models.IntegerField(blank=True, null=True)),
                ('OverallPlace', models.IntegerField(blank=True, null=True)),
                ('GenderPlace', models.IntegerField(blank=True, null=True)),
                ('BQ_2013', models.IntegerField(blank=True, null=True)),
                ('BQ_2020', models.IntegerField(blank=True, null=True)),
                ('BQ_2026', models.IntegerField(blank=True, null=True)),
                ('TotalParticipants', models.IntegerField(blank=True, null=True)),
                ('Date', models.CharField(blank=True, max_length=30, null=True)),
                ('RaceCity', models.CharField(blank=True, max_length=100, null=True)),
                ('RaceState', models.CharField(blank=True, max_length=20, null=True)),
                ('RaceCountry', models.CharField(blank=True, max_length=50, null=True)),
                ('BQ', models.BooleanField(default=False)),
                ('Qualified', models.BooleanField(default=False)),
                ('Buffer', models.IntegerField(blank=True, null=True)),
                ('Count', models.IntegerField(blank=True, null=True)),
                ('Run_2025', models.BooleanField(default=False)),
                ('Distance_to_Boston_mi', models.FloatField(blank=True, null=True)),
                ('Race_Distance_to_Boston_mi', models.FloatField(blank=True, null=True)),
                ('Ran_Boston_2024', models.BooleanField(default=False)),
                ('Avg_Buffer', models.IntegerField(blank=True, null=True)),
                ('buffer_0_500', models.BooleanField(default=False)),
                ('buffer_500_1000', models.BooleanField(default=False)),
                ('buffer_1000_1500', models.BooleanField(default=False)),
                ('buffer_1500_2000', models.BooleanField(default=False)),
                ('buffer_2000_plus', models.BooleanField(default=False)),
            ],
        ),
    ]
