# Generated by Django 5.2.6 on 2025-10-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bostonqualifier',
            name='Avg_Buffer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bostonqualifier',
            name='Buffer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
