# Generated by Django 5.2.6 on 2025-10-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_bostonqualifier_avg_buffer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='Age_Group',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='BQ',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='BQ_2013',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='BQ_2020',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='BQ_2026',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='City',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='Distance_to_Boston_mi',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='Finish',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='GenderPlace',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='OverallPlace',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='Qualified',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='RaceCity',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='RaceCountry',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='RaceState',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='State',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='TotalParticipants',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='Zip',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='buffer_0_500',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='buffer_1000_1500',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='buffer_1500_2000',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='buffer_2000_plus',
        ),
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='buffer_500_1000',
        ),
        migrations.AlterField(
            model_name='bostonqualifier',
            name='Age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bostonqualifier',
            name='Gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bostonqualifier',
            name='Run_2025',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
