# Generated by Django 5.2.6 on 2025-10-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_bostonqualifier_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bostonqualifier',
            name='Age_Group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='BQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='BQ_2013',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='BQ_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='BQ_2026',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='Country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='Date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='Distance_to_Boston_mi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='Finish',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='GenderPlace',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='OverallPlace',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='Qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='RaceCity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='RaceCountry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='RaceState',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='State',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='TotalParticipants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='Zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='buffer_0_500',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='buffer_1000_1500',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='buffer_1500_2000',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='buffer_2000_plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bostonqualifier',
            name='buffer_500_1000',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bostonqualifier',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bostonqualifier',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bostonqualifier',
            name='Run_2025',
            field=models.BooleanField(default=False),
        ),
    ]
