# Generated by Django 5.2.6 on 2025-11-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_bostonqualifier_age_group_bostonqualifier_bq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bostonqualifier',
            name='Gender',
        ),
    ]
