# Generated by Django 5.2.6 on 2025-11-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_bostonqualifier_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bostonqualifier',
            name='Gender',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
